"""
Application constants for Todo Master

Defines configuration paths, limits, and other constant values used throughout
the application.
"""

import os
from pathlib import Path

# Application metadata
APP_NAME = "todo-master"
APP_VERSION = "1.0.0"
APP_AUTHOR = "Todo Master Team"

# Storage configuration (FR-053 to FR-055)
CONFIG_DIR = Path.home() / ".config" / "todo-master"
TASKS_FILE = CONFIG_DIR / "tasks.json"
PROJECTS_FILE = CONFIG_DIR / "projects.json"
SETTINGS_FILE = CONFIG_DIR / "settings.json"
BACKUP_DIR = CONFIG_DIR / "backups"

# Performance and limits (FR-071, FR-072, FR-075)
MIN_TERMINAL_WIDTH = 80
MIN_TERMINAL_HEIGHT = 24
RECOMMENDED_TERMINAL_WIDTH = 120
RECOMMENDED_TERMINAL_HEIGHT = 40
MAX_TASKS_FOR_SMOOTH_RENDERING = 1000

# Auto-save and backup configuration (FR-056, FR-057)
AUTO_SAVE_INTERVAL_SECONDS = 5
BACKUP_COUNT = 5
UNDO_TIMEOUT_SECONDS = 5

# Task constraints (FR-002, FR-013)
MIN_TASK_TITLE_LENGTH = 1
MAX_TASK_TITLE_LENGTH = 200
MIN_PROJECT_NAME_LENGTH = 1
MAX_PROJECT_NAME_LENGTH = 50

# Default values
DEFAULT_PROJECT = "Inbox"
DEFAULT_PRIORITY = "medium"
DEFAULT_THEME = "dark"
DEFAULT_DATE_FORMAT = "%Y-%m-%d"
DEFAULT_TIME_FORMAT = "24h"
DEFAULT_WEEK_START = "Monday"

# UI Constants
STATUS_BAR_HEIGHT = 1
HELP_MODAL_WIDTH = 60
HELP_MODAL_HEIGHT = 20
MODAL_PADDING = 2

# Color pair IDs (will be initialized in theme.py)
COLOR_NORMAL = 1
COLOR_SELECTED = 2
COLOR_PRIORITY_LOW = 3
COLOR_PRIORITY_MEDIUM = 4
COLOR_PRIORITY_HIGH = 5
COLOR_PRIORITY_URGENT = 6
COLOR_PROJECT_RED = 7
COLOR_PROJECT_GREEN = 8
COLOR_PROJECT_YELLOW = 9
COLOR_PROJECT_BLUE = 10
COLOR_PROJECT_MAGENTA = 11
COLOR_PROJECT_CYAN = 12
COLOR_PROJECT_WHITE = 13
COLOR_OVERDUE = 14
COLOR_STATUS_BAR = 15
COLOR_MODAL_BORDER = 16

# Screen identifiers
SCREEN_TASK_LIST = 0
SCREEN_PROJECTS = 1
SCREEN_CALENDAR = 2
SCREEN_TAGS = 3
SCREEN_STATS = 4
SCREEN_SETTINGS = 5

# Performance targets (for monitoring)
TARGET_RENDER_TIME_MS = 50
TARGET_SEARCH_TIME_MS = 1000
TARGET_STARTUP_TIME_MS = 2000
TARGET_SCREEN_TRANSITION_MS = 500

__all__ = [
    "APP_NAME",
    "APP_VERSION",
    "APP_AUTHOR",
    "CONFIG_DIR",
    "TASKS_FILE",
    "PROJECTS_FILE",
    "SETTINGS_FILE",
    "BACKUP_DIR",
    "MIN_TERMINAL_WIDTH",
    "MIN_TERMINAL_HEIGHT",
    "RECOMMENDED_TERMINAL_WIDTH",
    "RECOMMENDED_TERMINAL_HEIGHT",
    "MAX_TASKS_FOR_SMOOTH_RENDERING",
    "AUTO_SAVE_INTERVAL_SECONDS",
    "BACKUP_COUNT",
    "UNDO_TIMEOUT_SECONDS",
    "MIN_TASK_TITLE_LENGTH",
    "MAX_TASK_TITLE_LENGTH",
    "MIN_PROJECT_NAME_LENGTH",
    "MAX_PROJECT_NAME_LENGTH",
    "DEFAULT_PROJECT",
    "DEFAULT_PRIORITY",
    "DEFAULT_THEME",
    "DEFAULT_DATE_FORMAT",
    "DEFAULT_TIME_FORMAT",
    "DEFAULT_WEEK_START",
    "STATUS_BAR_HEIGHT",
    "HELP_MODAL_WIDTH",
    "HELP_MODAL_HEIGHT",
    "MODAL_PADDING",
    "COLOR_NORMAL",
    "COLOR_SELECTED",
    "COLOR_PRIORITY_LOW",
    "COLOR_PRIORITY_MEDIUM",
    "COLOR_PRIORITY_HIGH",
    "COLOR_PRIORITY_URGENT",
    "COLOR_PROJECT_RED",
    "COLOR_PROJECT_GREEN",
    "COLOR_PROJECT_YELLOW",
    "COLOR_PROJECT_BLUE",
    "COLOR_PROJECT_MAGENTA",
    "COLOR_PROJECT_CYAN",
    "COLOR_PROJECT_WHITE",
    "COLOR_OVERDUE",
    "COLOR_STATUS_BAR",
    "COLOR_MODAL_BORDER",
    "SCREEN_TASK_LIST",
    "SCREEN_PROJECTS",
    "SCREEN_CALENDAR",
    "SCREEN_TAGS",
    "SCREEN_STATS",
    "SCREEN_SETTINGS",
    "TARGET_RENDER_TIME_MS",
    "TARGET_SEARCH_TIME_MS",
    "TARGET_STARTUP_TIME_MS",
    "TARGET_SCREEN_TRANSITION_MS",
]
